from .main_menu import get_main_menu_keyboard, get_analysis_menu_keyboard, get_exit_confirmation_keyboard
from .strategy import get_strategy_keyboard
from .admin import get_admin_receipt_keyboard
from .feedback import get_rating_keyboard, get_restart_keyboard